version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3-stretch-node-browsers

    steps:
      - checkout

      - run: sudo apt update && sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo docker-php-ext-install zip

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.lock" }}
            - v1-dependencies-

      - run: cp .env.testing .env
      - run: composer install -n --ignore-platform-reqs
      - run: php artisan key:generate
      - run: php artisan dusk:chrome-driver

      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor

      - restore_cache:
          keys:
            - node-v4-{{ checksum "package.json" }}
            - node-v4-

      - run: npm install

      - save_cache:
          key: node-v4-{{ checksum "package.json" }}
          paths:
            - node_modules
            - ~/.yarn

      - run: touch storage/testing.sqlite
      - run: php artisan migrate --env=testing --database=sqlite_testing --force
      - run: vendor/bin/phpunit
      - run: php artisan db:seed
      - run:
        name: Start Chrome Driver
        command: ./vendor/laravel/dusk/bin/chromedriver-linux
        background: true
      - run:
          name: Run Laravel Server
          command: php artisan serve
          background: true
      - run:
        name: Run Laravel Dusk Tests
        command: php artisan dusk
      - store_artifacts:
          path: tests/Browser/screenshots
      - store_test_results:
          path: tests/_output
      - store_artifacts:
          path: tests/_output
